### PR TITLE
Fix branch picker showing in non git projects

### LINKED ISSUE #179: Toolbar branch selector shows when no git repo
### Description

image

This is in a non-git repo

### To Reproduce

1. Open a non-git folder
2. The branch selector bugs out

### Expected behavior

The branch selector shows that [] like icon, like xcode.

### Version information

Aurora Editor: [e.g. 1.0]
Hash: [e.g. d06fb30e72634048395b5dbcdbc756b7f8ecc2f0]
MacOS: [e.g. 12.3.0]
Xcode: [e.g. 13.3]

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by nanashili**
# Description
When a project is open and it was not a git repo, the branch picker would still show but show and empty list/branches.

This PR fixes that issues and removes the popover view if certain requirements aren't met.

# Related Issue

* Fixes #179 

# Checklist

- [X] I read and understood the [contributing guide](https://github.com/AuroraEditor/AuroraEditor/blob/main/CONTRIBUTING.md) as well as the [code of conduct](https://github.com/AuroraEditor/AuroraEditor/blob/main/CODE_OF_CONDUCT.md)
- [X] My changes generate no new warnings
- [X] My code builds and runs on my machine
- [X] I documented my code
- [X] Review requested

# Screenshots

### CODE REVIEW

File: AuroraEditor/Base/Toolbar/UI/ToolbarBranchPicker.swift [hunk 1]
```diff
@@ -24,6 +24,9 @@ public struct ToolbarBranchPicker: View {
     @ObservedObject
     private var prefs: AppPreferencesModel = .shared
 
+    @ObservedObject
+    private var changesModel: SourceControlModel
```
Comment (KaiTheRedNinja) [inline AuroraEditor/Base/Toolbar/UI/ToolbarBranchPicker.swift:28]: SourceControlModel contains a GitClient so might want to delete gitclient

**Review by wdg — APPROVED** [review]

**Review by KaiTheRedNinja — APPROVED** [review]
